FROM debian:bookworm-slim

ENV LANG=C.UTF-8
ENV LC_ALL=C.UTF-8
ENV TZ=Europe/Berlin
ENV DEBIAN_FRONTEND=noninteractive

ARG USER_NAME=app
ARG USER_HOME=/app
ARG USER_ID=1000

RUN groupadd "$USER_NAME" && useradd -m -u "$USER_ID" -d "$USER_HOME" -g "$USER_NAME" "$USER_NAME"

RUN apt-get -o Acquire::Retries=3 -o APT::Update::Error-Mode=any update \
    && apt-get install -y --no-install-recommends \
        ca-certificates \
        make \
        pandoc \
        texlive-base \
        texlive-fonts-recommended \
        texlive-lang-english \
        texlive-lang-german \
        texlive-latex-base \
        texlive-latex-extra \
        texlive-latex-recommended \
        texlive-luatex \
        texlive-xetex \
        unzip \
        wget \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

# texcount
WORKDIR /
RUN wget -q -O texcount.zip mirrors.ctan.org/support/texcount.zip \
    && unzip -q texcount.zip \
    && rm texcount.zip \
    && chmod 755 texcount/texcount.pl
ENV PATH="$PATH:/texcount"

USER 1000
WORKDIR /app

CMD ["make"]
